#!/bin/bash

# (C) Copyright 1996- ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.


set -e

while test $# -gt 0; do

  case "$1" in
    --*)
    INFERO_RUN_MPI_ARGS="${INFERO_RUN_MPI_ARGS} $1"
    shift # past argument
    ;;
    -n|-np)
    INFERO_RUN_NPROCS="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    break
    ;;
  esac
done

command_exists() {
  type "$1" &> /dev/null ;
}

if [ -n "${INFERO_RUN_NTHREADS}" ]; then
  echo + export OMP_NUM_THREADS=${INFERO_RUN_NTHREADS}
  export OMP_NUM_THREADS=${INFERO_RUN_NTHREADS}
fi

if command_exists aprun            && \
  [[ ${EC_queue:-unset} != "nf" ]] && \
  [[ ${EC_queue:-unset} != "ns" ]]
then
  LAUNCH="aprun ${INFERO_RUN_MPI_ARGS}"
  if [ -z "${INFERO_RUN_NPROCS}" ]; then
     LAUNCH="${LAUNCH} -n 1"
  else
    LAUNCH="${LAUNCH} -n ${INFERO_RUN_NPROCS}"
  fi
  if [ -n "${OMP_NUM_THREADS}" ]; then
    LAUNCH="${LAUNCH} -d ${OMP_NUM_THREADS}"
  fi

elif command_exists srun ; then
  LAUNCH="srun ${INFERO_RUN_MPI_ARGS}"
  if [ -n "${INFERO_RUN_NGPUS}" ]; then
    LAUNCH="${LAUNCH} --gres=gpu:${INFERO_RUN_NGPUS}"
  fi
  if [ -z "${INFERO_RUN_NPROCS}" ]; then
    LAUNCH="${LAUNCH} -n 1"
  else
    LAUNCH="${LAUNCH} -n ${INFERO_RUN_NPROCS}"
  fi
  SLURM_EXPORT_ENV=ALL # Required to propagate environment variables to srun'd program

else
  if [[ ${ARCH:-unset} == "cray" ]]; then
    echo + module load cray-snplauncher
    module load cray-snplauncher
  fi
  if [ -z "${INFERO_RUN_NPROCS}" ]; then
    unset LAUNCH
  elif command_exists mpirun ; then
    LAUNCH="mpirun ${INFERO_RUN_MPI_ARGS} -np ${INFERO_RUN_NPROCS}"
  elif command_exists mpiexec; then
    LAUNCH="mpiexec ${INFERO_RUN_MPI_ARGS} -n ${INFERO_RUN_NPROCS}"
  else
    echo "No MPI driver found (mpirun,mpiexec,aprun,srun)"
    exit 1
  fi
fi

if [ -z "${INFERO_RUN_NPROCS}" ]; then
  echo + export ECKIT_MPI_FORCE=serial
  export ECKIT_MPI_FORCE=serial
fi

echo + $LAUNCH "$@"
$LAUNCH "$@"

